general {
	uid = "abc"
	db_path = "/config/owntone/dbase_and_logs/songs3.db"
	logfile = "/config/owntone/dbase_and_logs/owntone.log"
	loglevel = log
	admin_password = "owntoneadmin8765"
	websocket_port = 3688
	trusted_networks = { "localhost", "192.168", "172.17", "172.30" }
	ipv6 = no
	cache_dir = "/config/owntone/dbase_and_logs/cache"
}

library {
	name = "AirSpot Bridge"
	port = 3689
	directories = { "/music" }
	podcasts = { "/Podcasts" }
	audiobooks = { "/Audiobooks" }
	compilations = { "/Compilations" }
	compilation_artist = "Various Artists"
	pipe_autostart = true
}

audio {
	nickname = "None"
	type = "pulseaudio"
}

airplay_shared {
	control_port = 3690
	timing_port = 3691
}

spotify {
}

mpd {
	port = 0
}

streaming {
	sample_rate = 48000
	bit_rate = 320
}
